
# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=order-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# event service
event-service.url=http://localhost:80871

# payment Gateway
payment-gateway.url=http://localhost:8080

# order service config
 reservation.ttl-minutes=15
